version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing npm packages from package.json"
      #- npm install prettier
      - npm install
      #- npm install babel-eslint
  pre_build:
    commands:
      - echo "Testing pipeline code"
      - make pipeline_test
  build:
    commands:
      - npm run build
      - echo "Deploying staging pipeline"
      - cdk deploy staging -c env=$ENV

    