version: 0.2

env:
  variables:
    TEST: "Hello world"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo $TEST
      - echo "Installing linting and styling packages"
      - pip install isort flake8 pylint
  build:
    commands:
      - isort src/api/*.py
      - flake8 src/api/
      - pylint src/api/*.py
      - echo $TEST
      