version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Installing npm packages from package.json"
      - npm install -g aws-cdk
      - cdk --version
      - make js-install
      # - npm install prettier
      # - npm install babel-eslint
  pre_build:
    commands:
      - echo "Testing pipeline code"
      - make pipeline_test
  build:
    commands:
      - npm run build-infra
      - echo "Deploying staging pipeline"
      - cdk deploy staging -c env=$ENV
