version: 0.2

env:
  variables:
    SAM_BUCKET: meal-planner-demo-bucket
    
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing linting and styling packages"
      - make py-install
  pre_build:
    commands:
      - echo "Running styling packages..."
      - make py_test
  build:
    commands:
      - echo "Packaging SAM template"
      - make sam_package
artifacts:
  files:
    - '**/*'

