version: 0.2

env:
  variables:
    SAM_BUCKET: meal-planner-demo-bucket
    
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "Installing linting and styling packages"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running styling packages..."
      - make py_test
  post_build:
    commands:
      - echo "Packaging SAM template"
      - sam package --template-file template.yaml --s3-bucket $SAM_BUCKET --output-template-file packaged-template.yaml
artifacts:
  files:
    - '**/*'

